name: Build and test

on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # ...previous steps
      - run: npm run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
      # ...previous steps
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v3
        with:
           path: build/